name: Feature Request
description: Suggest a new feature or enhancement, e.g. "Add emojis introduced in macOS XYZ"
labels: ["feature-request"]
body:
  - type: textarea
    id: feature-description
    attributes:
      label: Feature Description
      description: Describe the feature you would like to see implemented in as much detail as possible.
      placeholder: Explain the feature and its benefits.
    validations:
      required: true
  - type: textarea
    id: problem-solved
    attributes:
      label: Problem Solved
      description: Describe the problem that this feature would solve or the use case it would address.
      placeholder: Explain the problem or use case.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you have considered.
      placeholder: List and describe any alternatives you have considered.
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context or screenshots about the feature request here.
      placeholder: e.g., screenshots, design mockups, etc.
  - type: markdown
    attributes:
      value: |
        Thank you for your suggestion! 🥳
